qa-tools/qa-tools

.travis.yml
This is not a testing step but an initialization step
=> Move the creation of the build folder to before_script on Travis

library/QATools/QATools/PageObject/Config/Config.php, library/QATools/QATools/PageObject/Exception/PageFactoryException.php, library/QATools/QATools/PageObject/PageFactory.php, library/QATools/QATools/PageObject/PageLocator/DefaultPageLocator.php, library/QATools/QATools/PageObject/PageLocator/IPageLocator.php, tests/QATools/QATools/PageObject/PageFactoryTest.php, tests/QATools/QATools/PageObject/PageLocator/DefaultPageLocatorTest.php
New PR to develop instead of master see #89.
Closes #12
=> Enhance getPage in PageFactory

library/QATools/QATools/PageObject/IPageFactory.php
Adds the `getPage` method to the `IPageFactory` interface
Closes #118
=> Added `getPage` to `IPageFactory`

library/QATools/QATools/HtmlElements/Proxy/TypifiedElementCollectionProxy.php, tests/QATools/QATools/HtmlElements/Proxy/TypifiedElementCollectionProxyTest.php, tests/QATools/QATools/HtmlElements/Proxy/TypifiedElementProxyTest.php, tests/QATools/QATools/PageObject/Proxy/AbstractProxyTestCase.php, tests/QATools/QATools/PageObject/Proxy/WebElementCollectionProxyTest.php, tests/QATools/QATools/PageObject/Proxy/WebElementProxyTest.php
=> Remove rewind

library/QATools/QATools/PageObject/ElementLocator/DefaultElementLocator.php, library/QATools/QATools/PageObject/Exception/ElementException.php, library/QATools/QATools/PageObject/Property.php, tests/QATools/QATools/BEM/ElementLocator/BEMElementLocatorTest.php, tests/QATools/QATools/PageObject/ElementLocator/DefaultElementLocatorTest.php, tests/QATools/QATools/PageObject/ElementLocator/WaitingElementLocatorTest.php, tests/QATools/QATools/PageObject/PropertyTest.php
=> Implementation of quantity check for locator

docs/annotations.rst, docs/getting-started.rst, library/QATools/QATools/PageObject/Url/Builder.php, tests/QATools/QATools/PageObject/Url/BuilderTest.php, tests/QATools/QATools/PageObject/Url/ParserTest.php
=> Added support for ports

.travis.yml, composer.json, composer.lock, tests/QATools/QATools/HtmlElements/Element/AbstractElementContainerTest.php, tests/QATools/QATools/Live/HtmlElements/Element/FormTest.php, tests/QATools/QATools/PageObject/Element/WebElementTest.php
Failed PHP7 build (due `paratest` incompatibility): https://travis-ci.org/qa-tools/qa-tools/jobs/63512286
Sort of passed test (using `phpunit` directly): https://travis-ci.org/qa-tools/qa-tools/jobs/63516774
=> Add PHP 7 support

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Improvements to README and other docs based on information from http://williamdurand.fr/2013/07/04/on-open-sourcing-libraries/ .
=> Various README improvements to explain what project is

library/QATools/QATools/HtmlElements/Proxy/TypifiedElementCollectionProxy.php
=> The typified collection proxy now sets name on proxied typified collection

library/QATools/QATools/PageObject/PropertyDecorator/DefaultPropertyDecorator.php, tests/QATools/QATools/HtmlElements/PropertyDecorator/TypifiedPropertyDecoratorTest.php, tests/QATools/QATools/PageObject/PropertyDecorator/DefaultPropertyDecoratorTest.php
=> Proxy the WebElementCollection class elements using designated proxy

CHANGELOG.md
=> Adding a change log file

docs/Makefile
=> The "docs/make livehtml" now listens on all IP addresses

tests/run_selenium.sh
=> Use latest Selenium Server version

CHANGELOG.md, library/QATools/QATools/HtmlElements/Proxy/TypifiedElementCollectionProxy.php, library/QATools/QATools/HtmlElements/Proxy/TypifiedElementProxy.php, library/QATools/QATools/PageObject/Proxy/WebElementCollectionProxy.php, library/QATools/QATools/PageObject/Proxy/WebElementProxy.php, tests/QATools/QATools/BEM/Proxy/BlockProxyTest.php, tests/QATools/QATools/BEM/Proxy/ElementProxyTest.php, tests/QATools/QATools/HtmlElements/Proxy/ElementContainerProxyTest.php, tests/QATools/QATools/HtmlElements/Proxy/TypifiedElementCollectionProxyTest.php, tests/QATools/QATools/HtmlElements/Proxy/TypifiedElementProxyTest.php, tests/QATools/QATools/PageObject/Element/AbstractElementCollectionTestCase.php, tests/QATools/QATools/PageObject/Proxy/AbstractProxyTestCase.php, tests/QATools/QATools/PageObject/Proxy/ElementContainerProxyTest.php, tests/QATools/QATools/PageObject/Proxy/WebElementCollectionProxyTest.php, tests/QATools/QATools/PageObject/Proxy/WebElementProxyTest.php
=> Test default proxied class only, whe appropriate

CHANGELOG.md, library/QATools/QATools/PageObject/Proxy/AbstractProxy.php, tests/QATools/QATools/BEM/Fixture/Element/BlockChild.php, tests/QATools/QATools/BEM/Fixture/Element/ElementChild.php, tests/QATools/QATools/BEM/Proxy/BlockProxyTest.php, tests/QATools/QATools/BEM/Proxy/ElementProxyTest.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementCollectionChild.php, tests/QATools/QATools/PageObject/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementCollectionChild.php, tests/QATools/QATools/PageObject/Proxy/AbstractProxyTestCase.php, tests/QATools/QATools/PageObject/Proxy/WebElementProxyTest.php
=> Support for dynamic method calls forwarding from proxy to the element

library/QATools/QATools/PageObject/Element/AbstractElementContainer.php, library/QATools/QATools/PageObject/Element/WebElement.php, tests/QATools/QATools/BEM/Element/BlockTest.php, tests/QATools/QATools/HtmlElements/Element/FormTest.php, tests/QATools/QATools/Live/HtmlElements/Element/TypifiedElementTestCase.php, tests/QATools/QATools/PageObject/Element/AbstractElementContainerTest.php, tests/QATools/QATools/PageObject/Element/WebElementTest.php, tests/QATools/QATools/PageObject/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementChild.php, tests/QATools/QATools/TestCase.php
=> Use composition instead of inheritance for "WebElement" construction

.travis.yml, composer.lock, tests/install_webserver.sh, tests/run_selenium.sh
=> Use Travis CI caches

library/QATools/QATools/PageObject/Proxy/AbstractProxy.php, tests/QATools/QATools/BEM/Fixture/Element/BlockChild.php, tests/QATools/QATools/BEM/Fixture/Element/ElementChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementCollectionChild.php, tests/QATools/QATools/PageObject/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementCollectionChild.php, tests/QATools/QATools/PageObject/Proxy/AbstractProxyTestCase.php
This is a bugfix to PR implementation of #169 task.
=> Exception thrown in proxied dynamic method wasn't properly wrapped with internal exception class

CHANGELOG.md, library/QATools/QATools/PageObject/Exception/ElementException.php, library/QATools/QATools/PageObject/Proxy/AbstractProxy.php, library/QATools/QATools/PageObject/Proxy/IProxy.php, tests/QATools/QATools/BEM/Fixture/Element/BlockChild.php, tests/QATools/QATools/BEM/Fixture/Element/ElementChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementChild.php, tests/QATools/QATools/HtmlElements/Fixture/Element/TypifiedElementCollectionChild.php, tests/QATools/QATools/Live/PageObject/Element/InputContainer.php, tests/QATools/QATools/Live/PageObject/PageTest.php, tests/QATools/QATools/Live/PageObject/Pages/WebElementPage.php, tests/QATools/QATools/PageObject/Fixture/Element/ElementContainerChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementChild.php, tests/QATools/QATools/PageObject/Fixture/Element/WebElementCollectionChild.php, tests/QATools/QATools/PageObject/Proxy/AbstractProxyTestCase.php
=> Property forwarding support in proxies

library/QATools/QATools/HtmlElements/Element/AbstractTypifiedElement.php, library/QATools/QATools/HtmlElements/Element/Form.php, library/QATools/QATools/HtmlElements/Element/LabeledElement.php, library/QATools/QATools/HtmlElements/Element/Select.php, library/QATools/QATools/PageObject/Element/WebElement.php, library/QATools/QATools/PageObject/SeleniumSelector.php, tests/QATools/QATools/HtmlElements/Element/AbstractTypifiedElementTest.php, tests/QATools/QATools/HtmlElements/Element/FormTest.php, tests/QATools/QATools/HtmlElements/Element/LabeledElementTest.php, tests/QATools/QATools/HtmlElements/Element/SelectTest.php, tests/QATools/QATools/PageObject/Element/WebElementTest.php
=> Use escape literal

library/QATools/QATools/PageObject/PageFactory.php, library/QATools/QATools/PageObject/SeleniumSelector.php, tests/QATools/QATools/Live/HtmlElements/Element/TypifiedElementTestCase.php, tests/QATools/QATools/PageObject/SeleniumSelectorTest.php
=> Use "CssSelector" directly in "SeleniumSelector"

CHANGELOG.md, composer.json, composer.lock, docs/examples/config_base_url.php, docs/getting-started.rst, docs/howto.rst, library/QATools/QATools/BEM/BEMPageFactory.php, library/QATools/QATools/HtmlElements/TypifiedPageFactory.php, library/QATools/QATools/PageObject/Container.php, library/QATools/QATools/PageObject/PageFactory.php, tests/QATools/QATools/PageObject/ContainerTest.php, tests/QATools/QATools/PageObject/PageFactoryTest.php
=> Use DIC for PageFactory dependency management

CHANGELOG.md, docs/annotations.rst, library/QATools/QATools/PageObject/Exception/MissingParametersException.php, library/QATools/QATools/PageObject/Url/Builder.php, tests/QATools/QATools/PageObject/Exception/MissingParametersExceptionTest.php, tests/QATools/QATools/PageObject/Url/BuilderTest.php
=> Implemented @page-url unmasking

CHANGELOG.md, library/QATools/QATools/HtmlElements/Element/Button.php, tests/QATools/QATools/HtmlElements/Element/AbstractTypifiedElementTest.php, tests/QATools/QATools/HtmlElements/Element/ButtonTest.php, tests/QATools/QATools/TestCase.php
=> Add image inputs to button acceptance criteria

CHANGELOG.md, docs/examples/config_base_url.php, docs/getting-started.rst, library/QATools/QATools/BEM/BEMPageFactory.php, library/QATools/QATools/HtmlElements/TypifiedPageFactory.php, library/QATools/QATools/PageObject/PageFactory.php, tests/QATools/QATools/Live/AbstractLivePageTestCase.php, tests/QATools/QATools/Live/HtmlElements/Pages/RelativePage.php, tests/QATools/QATools/Live/HtmlElements/TypifiedPageTest.php, tests/QATools/QATools/Live/PageObject/PageTest.php, tests/QATools/QATools/Live/PageObject/Pages/RelativePage.php, tests/QATools/QATools/PageObject/PageFactoryTest.php
=> Fixed error, when constructing "PageFactory" with Config object

.travis.yml, composer.lock, tests/run_selenium.sh
Changes made:
1. fixed PHP 5.3 build
2. added PHP 7.1 to build
3. using Chrome instead of Firefox (because getting error from Firefox binary)
---
https://travis-ci.org/qa-tools/qa-tools/jobs/281754328
```
(firefox:3819): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
//bin/dbus-launch terminated abnormally without any error message
process 3819: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
```
=> Fix Travis CI builds after OS upgrade

library/QATools/QATools/PageObject/PropertyDecorator/DefaultPropertyDecorator.php
For issue #196 I've noticed that there are instances of `is_null` in your code base. If you'd like I could create a separate PR for that.
=> Added strict comparison to null

.travis.yml, tests/run_selenium.sh
See https://benlimmer.com/2019/01/14/travis-ci-xvfb/
=> Fixes XVFB starting issue on Travis CI
